name: Release

on:
  release:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker build
      run: docker build -t latest .
    - name: Docker login
      run: docker login -u w2322402411 --password ${{ secrets.DOCKERHUB_TOCKEN }}
    - name: Push container
      run: docker push w2322402411/csi5112project:latest
